---
# roles/certbot/handlers/main.yml

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  become: true
  failed_when: false

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true
  failed_when: false

- name: reload postfix
  ansible.builtin.systemd:
    name: postfix
    state: reloaded
  become: true
  failed_when: false

- name: reload dovecot
  ansible.builtin.systemd:
    name: dovecot
    state: reloaded
  become: true
  failed_when: false
